const {cities,places,schedule=[]}=window.APP_DATA;let map,userMarker,userWatch,markers=[];const $=s=>document.querySelector(s);const esc=s=>(s||'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function renderCities(){cityGrid.innerHTML=cities.map(c=>`<button class="city-card" ${c.status==='ready'?'':'disabled'} data-city="${esc(c.name)}"><div class="city-art">${esc(c.name)}</div><div class="city-body"><span class="badge">${c.status==='ready'?'Open guide':'Coming next'}</span><div class="city-country">${esc(c.country)}</div><div class="city-dates">${esc(c.dates)}</div><div class="meta">${esc(c.note||"")}</div></div></button>`).join('');document.querySelectorAll('[data-city="Paris"]').forEach(b=>b.onclick=openParis)}
function openParis(){homeView.classList.add('hidden');parisView.classList.remove('hidden');backBtn.classList.remove('hidden');pageTitle.textContent='Paris';pageSub.textContent='Live map, walks and stories';setTimeout(initMap,50)}
backBtn.onclick=()=>{parisView.classList.add('hidden');homeView.classList.remove('hidden');backBtn.classList.add('hidden');pageTitle.textContent="Barry's Europe Guide";pageSub.textContent='History, hidden gems and questionable trivia'};
function initMap(){if(map){map.invalidateSize();return}map=L.map('map').setView([48.8566,2.3522],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);addMarkers();}
const colors={'Major landmark':'#17324d','Major museum':'#17324d','Restaurant':'#9b2f45','Dinner reservation':'#9b2f45','Garden / TV location':'#39845b','Garden / photo':'#39845b','Viewpoint':'#c4882f','Bridge / photo':'#c4882f','TV location':'#7c4ba5','Bakery / TV location':'#7c4ba5','Groceries':'#697780'};
function addMarkers(filter=''){markers.forEach(m=>map.removeLayer(m));markers=[];places.filter(p=>p.lat&&(!filter||p.group===filter)).forEach((p,i)=>{const color=colors[p.category]||'#2e6f9e';const icon=L.divIcon({className:'',html:`<div class="marker-dot" style="background:${color}"></div>`,iconSize:[14,14]});const m=L.marker([p.lat,p.lng],{icon}).addTo(map).bindPopup(`<b>${esc(p.name)}</b><br><small>${esc(p.category)}</small><br><button onclick="showPlace(${places.indexOf(p)})">Open details</button>`);markers.push(m)})}
locateBtn.onclick=()=>{if(!navigator.geolocation){locationMsg.textContent='Location is not supported on this device.';return}locationMsg.textContent='Finding your location…';navigator.geolocation.getCurrentPosition(showLocation,locationError,{enableHighAccuracy:true,timeout:12000});if(userWatch)navigator.geolocation.clearWatch(userWatch);userWatch=navigator.geolocation.watchPosition(showLocation,()=>{},{enableHighAccuracy:true,maximumAge:5000})};
function showLocation(pos){const ll=[pos.coords.latitude,pos.coords.longitude];if(!userMarker){userMarker=L.circleMarker(ll,{radius:9,color:'#fff',weight:3,fillColor:'#1677ff',fillOpacity:1}).addTo(map).bindPopup('You are here')}else userMarker.setLatLng(ll);map.setView(ll,16);locationMsg.textContent=`Location found · accuracy about ${Math.round(pos.coords.accuracy)} m`;}
function locationError(e){locationMsg.textContent=e.code===1?'Location permission was denied. Allow location for this site in Safari settings.':'Your location could not be found.'}
function renderPlaces(){const groups=[...new Set(places.map(p=>p.group))];groupFilter.innerHTML='<option value="">All areas</option>'+groups.map(g=>`<option>${esc(g)}</option>`).join('');filterPlaces()}
function filterPlaces(){const q=searchBox.value.toLowerCase(),g=groupFilter.value;const list=places.filter(p=>(!g||p.group===g)&&(!q||(p.name+' '+p.description+' '+p.category).toLowerCase().includes(q)));placeList.innerHTML=list.map(p=>`<article class="place-card" onclick="showPlace(${places.indexOf(p)})"><h3>${esc(p.name)}</h3><div class="meta">${esc(p.address)}</div><div class="chips"><span class="chip">${esc(p.category)}</span><span class="chip">${esc(p.group)}</span></div></article>`).join('')||'<div class="notice">No places match that search.</div>'}
searchBox.oninput=filterPlaces;groupFilter.onchange=filterPlaces;
function renderWalks(){const groups=[...new Set(places.map(p=>p.group))].filter(g=>g!=='Food and practical');walkList.innerHTML=groups.map(g=>{const n=places.filter(p=>p.group===g).length;return`<article class="walk-card"><h3>${esc(g)}</h3><div class="meta">${n} saved and suggested stops</div><button class="primary" onclick="showWalk('${g.replace(/'/g,"\\'")}')">Show on map</button></article>`}).join('')}
window.showWalk=g=>{document.querySelector('[data-panel="mapPanel"]').click();addMarkers(g);const pts=places.filter(p=>p.group===g&&p.lat).map(p=>[p.lat,p.lng]);if(pts.length)map.fitBounds(pts,{padding:[30,30]})};
window.showPlace=i=>{const p=places[i];const q=encodeURIComponent(p.name+' '+p.address);const directions=`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(p.address)}&travelmode=walking`;const maps=`https://www.google.com/maps/search/?api=1&query=${q}`;const research=`https://www.google.com/search?q=${encodeURIComponent(p.name+' Paris history interesting facts')}`;sheetContent.innerHTML=`<div class="meta">${esc(p.group)} · ${esc(p.category)}</div><h2>${esc(p.name)}</h2><div class="meta">${esc(p.address)}</div><p>${esc(p.description)}</p><div class="actions"><a href="${directions}" target="_blank">Walking directions</a><a href="${maps}" target="_blank">Google Maps</a>${p.website?`<a class="secondary" href="${p.website}" target="_blank">Official website</a>`:''}<a class="secondary" href="${research}" target="_blank">Further research</a></div>`;sheet.classList.remove('hidden')};
closeSheet.onclick=()=>sheet.classList.add('hidden');sheet.onclick=e=>{if(e.target===sheet)sheet.classList.add('hidden')};
document.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.segmented button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.panel').forEach(p=>p.classList.add('hidden'));$('#'+b.dataset.panel).classList.remove('hidden');if(b.dataset.panel==='mapPanel'&&map)setTimeout(()=>map.invalidateSize(),20)});
function renderSchedule(){scheduleList.innerHTML=schedule.map((s,i)=>`<article class="schedule-card"><div class="schedule-date">${esc(s.date)}</div><div class="schedule-row"><div class="schedule-time">${esc(s.time)}</div><div><h3>${esc(s.title)}</h3><div class="meta">${esc(s.details||'')}</div><span class="chip">${esc(s.type)}</span></div></div></article>`).join('')||'<div class="notice">No scheduled items yet.</div>'}
renderCities();renderPlaces();renderWalks();renderSchedule();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));